import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import test from 'node:test';

test('post export stays simple with quote and vote images in three finishes', async () => {
  const app = await readFile(new URL('../app.js', import.meta.url), 'utf8');
  const exporter = app.slice(app.indexOf('async function openPostDownload'), app.indexOf('function openEditPost'));
  assert.match(exporter, /selectExportFormat/);
  assert.match(exporter, /authorAvatarUrl/);
  assert.match(exporter, /data-export-background="transparent"/);
  assert.match(exporter, /backgroundMode === 'brand'/);
  assert.doesNotMatch(exporter, /badgeX|#2296f3/);
  assert.match(exporter, /drawQuoteExport/);
  assert.match(exporter, /drawVoteExport/);
  assert.match(exporter, /-quote\.png/);
  assert.match(exporter, /-votes\.png/);
  assert.match(exporter, /No background/);
  assert.match(exporter, /Callout background/);
  assert.match(exporter, /Glass overlay/);
  assert.match(exporter, /data-export-background="glass"/);
  assert.match(exporter, /finish === 'glass'/);
  assert.match(exporter, /rgba\(255,255,255,\.52\)/);
  assert.match(exporter, /Download both images/);
  assert.doesNotMatch(exporter, /Top Takes/);
  assert.doesNotMatch(exporter, /TikTok overlay/);
  assert.match(exporter, /'#55df50', 'BASED', 'based'/);
  assert.match(exporter, /drawCompactVote\(inner, basedWidth, '#55df50', 'BASED', 'based'\)/);
  assert.match(exporter, /drawCompactVote\(hotButtonX, hotWidth, '#ff5431', 'HOT TAKE', 'hot'\)/);
  assert.match(exporter, /compactBarWidth \* based \/ 100/);
  assert.match(exporter, /drawBasedExportGlyph/);
  assert.doesNotMatch(exporter, /fillText\('TOP TAKES'/);
  assert.doesNotMatch(exporter, /voteLabel/);
  assert.match(exporter, /barWidth \* based \/ 100/);
  assert.doesNotMatch(exporter, /emojiReactions|postReactions/);
});
